[email]
name="miajio" # 发送者邮件名称
mailAddr="miajio@163.com" # 发送者邮件地址
smtpAddr="smtp.163.com:25"
hostAddr="smtp.163.com"
password="XXXXXXXXXXXX" # 邮箱授权码

[mysql]
host="127.0.0.1:3306" # 数据库地址
user="root" # 数据库用户名
password="123456" # 数据库密码
database="miajiodb" # 数据库名
charset="utf8mb4" # 字符集
parseTime="True" # 是否格式化时间
loc="Local" # 时区

[redis]
host="127.0.0.1:6379" # redis 服务器地址
password="" # redis 密码
db=0 # 默认连接库

[server]
jwtKey="testok jwt"
port=":8080" # 服务端口
useHttps=false # 是否使用https
httpsKey="./miajio.com_other/miajio.com.key"
httpsPem="./miajio.com_other/miajio.com_bundle.pem"
httpsHost="https://www.miajio.com"