[mysql]
host="127.0.0.1:3306" # 数据库地址
user="root" # 数据库用户名
password="123456" # 数据库密码
database="test" # 数据库名
charset="utf8mb4" # 字符集
parseTime="True" # 是否格式化时间
loc="Local" # 时区

[server]
port=":81" # 服务端口
useHttps=false # 是否使用https
httpsKey="xxx.key"
httpsPem="xxx.pem"
httpsHost="https://www.miajio.com"
